
###
GET https://api.wordnik.com/v4/word.json/ostentatious/topExample?useCanonical=false&api_key=22bf12vddbpizrmyfs90cf695e9j4u1seq52o4klisqmqn6v2

###

GET https://api.coindesk.com/v1/bpi/currentprice.json

###
GET https://open.er-api.com/v6/latest/USD